version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: codeflix-app
    container_name: codeflix-app
    command: ./.docker/start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app